### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by MaxDesiatov** [meilisearch/meilisearch-swift#1]
Thanks for the great library! I wasn't able to find any mention of Linux in README and there's no Linux build set up on CI either. Is Linux supported in any way or are there any plans to support it in your roadmap?

**Comment by ppamorim** [comment]
@MaxDesiatov Hi,

Yes, we have plans to support it and it should work straightway. I was unable to test it but I suspect it may work because we are using only stuff from `Foundation`.

We are open for PR if you are interested in implementing the Linux build.

Thanks for the firs issue opened. :)
