### ISSUE TITLE
UpdateSetting() method erase settings not updated

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-swift#119]
**Description**
`updateSettings` seems to override all attributes that are not updated.

**Expected behavior**
Settings before using `updateSettings`:
```json
{"rankingRules":["typo","words","proximity","attribute","wordsPosition","exactness"],"distinctAttribute":null,"searchableAttributes":["*"],"displayedAttributes":["*"],"stopWords":[],"synonyms":{},"attributesForFaceting":[]}
```

**Current behavior**
Settings after using `updateSettings` this way:
```
client.updateSetting(UID: "movies", Setting(distinctAttribute: nil))
```
```json
{"rankingRules":[],"distinctAttribute":"nil","searchableAttributes":["*"],"displayedAttributes":["*"],"stopWords":[],"synonyms":{},"attributesForFaceting":[]}
```

**Environment:**
 - OS:  Apple OS X
 - MeiliSearch version: v.0.20.0
 - meilisearch-swift version: v0.7.0

**Comment by curquiza** [comment]
We should add tests for this behavior!
