### ISSUE TITLE
Add bors

### ISSUE THREAD

**Issue by ppamorim** [meilisearch/meilisearch-swift#120]
Title is self-explanatory. I am missing `bors try` here.

**Comment by curquiza** [comment]
Bors is already present in this repo and I see on the bors dashboard you have the right to `bors try`

**Comment by curquiza** [comment]
Where did you get the failure?

**Comment by curquiza** [comment]
Looks like it already works: https://github.com/meilisearch/meilisearch-swift/pull/118

I close this issue, sorry if I miss understood something
