### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch-swift#129]
The [documentation link](https://meilisearch.github.io/meilisearch-swift/) in the README is currently returning a 404. There is a [gh-pages](https://github.com/meilisearch/meilisearch-swift/tree/gh-pages) branch present so I'm guessing it is an issue in the pages section of settings?

**Comment by curquiza** [comment]
Thanks a lot @sanders41, we are working on it :)

**Comment by curquiza** [comment]
Fixed! 😄
