### ISSUE TITLE
Add page in CocoaPods for MeiliSearch

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-swift#131]
Currently, MeiliSearch can be searched and found in the CocoaPods search bar,

<img width="1412" alt="Capture d’écran 2021-05-06 à 15 23 28" src="https://user-images.githubusercontent.com/20380692/117305657-42385600-ae7f-11eb-89f9-521b41e21acb.png">

But we don't have a dedicated page in the CocoaPods website.

https://cocoapods.org/pods/MeiliSearch redirects to this GH repository for the moment.

**Comment by bidoubiwa** [comment]
The MeiliSearch page in cocoapods should at least have a copy of the readme.md

**Comment by brunoocasali** [comment]
CocoaPods redirects the user to Github. I don't think that's bad. Since we don't have time to work on this, I'll close this issue.
