### ISSUE TITLE
Add linting in tests and demos folder

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#137]
as pr #134  a linter is introduced but only in the source code. For consistency `Tests` and `Demos` folder should be lint-ed as well.

**Comment by ppamorim** [comment]
I will have to disable the lint `Explicit Type Interface Violation` because it's giving a false positive on Swift 5.4, [here](https://github.com/realm/SwiftLint/issues/3615). Is that ok?

**Comment by bidoubiwa** [comment]
Ah that's a shame! Yes lets disable it. Could you make a comment next to the rule in the config file explaining the false positive and maybe also a small issue explaining the issue so that we can track future updates of swiflint and update it when it is fixed? 

If you prefer not I can do the PR and the issue no problem :) Thanks for investigating !
