### ISSUE TITLE
Remove SQLITE_FILEPROTECTION warning on tests run

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#139]
**Description**
When tests are runned, warning are spammed: 

```
[logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags\
```

**Expected behavior**
Avoid warning spamming the console and making errors hard to spot.

**Current behavior**

A lot of the following warning:
```
[logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags\
```

**Possible solutions**

This [stackoverflow](https://stackoverflow.com/questions/65279008/swiftui-macos-fetch-json-error-logging-volume-does-not-support-data-protection)

**Comment by IgorChernyshov** [comment]
Hi there,

This pull request should fix the issue https://github.com/meilisearch/meilisearch-swift/pull/211
