### ISSUE TITLE
Guarantee compatibility with objective-c

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#148]
Looking at algolia's swift plugin, it is also compatible with objective-c. Maybe we could have the same compatibility.

It does not seem to be an easy task [following this article](https://www.algolia.com/blog/engineering/supporting-swift-objective-c/).

**Comment by ppamorim** [comment]
This is pretty possible. I don't think it would require much change.

**Comment by bidoubiwa** [comment]
Good to know!

**Comment by bidoubiwa** [comment]
Closing this issue. We will re-open it if it is requested
