### ISSUE TITLE
Should we provide errorcode and error type in case of failed request

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#149]
When a request is failed before reaching MeiliSearch an error is returned containing multiple information: 
```
Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x7fc477d07ea0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <985CB48F-12D1-4A3F-96B5-5F56AA32ED31>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <985CB48F-12D1-4A3F-96B5-5F56AA32ED31>.<1>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://localhost:7701/indexes/movi22es/documents?limit=20, NSErrorFailingURLKey=http://localhost:7701/indexes/movi22es/documents?limit=20, _kCFStreamErrorDomainKey=1}
```

In this error, tree information may be relevant to a swift developer: 
` Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server."`

We provide the third information, that is related to the error code. 

Nonetheless, should we also provide `domain` and `code` ?

Node: This has nothing to do with an error returned by MeiliSearch

**Comment by ppamorim** [comment]
@bidoubiwa It's returning the domain and code because it complies with the `NSURLSession` format and `NSError`. We could wrap this error and return a enum Meilisearch error instead relying on the return from the `NSURLSession`.

**Comment by bidoubiwa** [comment]
Im working on this here #145 I hope this will fix this
