### ISSUE TITLE
Fix typo on alt "GtiHub Workflow Status"

### ISSUE THREAD

**Issue by ppamorim** [meilisearch/meilisearch-swift#155]
If you open the README.md file it's written `GtiHub` in the alt description.

**Comment by curquiza** [comment]
Hello @ppamorim, thanks for this report!

Sorry I know you assigned yourself on this issue but it's been almost 3 weeks so I fix this typo in #161. Indeed, we don't really like letting known typo in our docs 🙂

Thanks a lot for noticing it! 🙏
