### ISSUE TITLE
The test CIs are failing

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-swift#238]
Currently, and randomly, the CI `integration-test` and `integraion-tests-against-rc` are failing. It uses the script which only fails in this CI. @bidoubiwa and I suspected it fails because of the `macos-latest` runner because the script works in every context except this one, but we don't really know why.

See the failing GH action: https://github.com/meilisearch/meilisearch-swift/runs/4190256299?check_suite_focus=true

**Comment by curquiza** [comment]
About what we don't use brew: because it takes time before a new version of MeiliSearch to be available in Brew. Right after a new MeiliSearch release, we don't really want to block our CIs and releases in this package, waiting for brew to integrate us.
Sometimes, we even had big issues that make us impossible to have MeiliSearch on brew for a version. So it's kind of risky to use brew in our CI I think.

**Comment by brunoocasali** [comment]
I will close this issue, since we don't expect any issues in the past months.
