### ISSUE TITLE
Run MeiliSearch Swift test against a real MeiliSearch server

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-swift#24]
As for my understanding, every single MeiliSearch test in this repository is being run on a mocked server, replacing/overriding the functions, and getting a mocked answer. Wouldn't it be better if we run a docker container with MeiliSearch's latest version and run the tests by making directly the requests to an actual MeiliSearch instance? What do you think @ppamorim ?

**Comment by ppamorim** [comment]
Hi @eskombro.

You be nice to have this working, I have plans to implement this as soon as we complete the facets filter and documentation. :)

**Comment by curquiza** [comment]
Closed by #32. This issue #49 details all the missing tests.
