### ISSUE TITLE
Filters are supposed to be a String.

### ISSUE THREAD

**Issue by ravisharmaa** [meilisearch/meilisearch-swift#246]
On the Swift documentation of 

https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#using-facets, it is described to use filter attributes as an array. However, pasting that exact code in the Xcode produces an error which states:

```Cannot convert value of type '[[String]]' to expected argument type 'String?'```

```swift
 let searchParameters = SearchParameters(
            query: "thriller",
            filter: [["genres = Horror", "genres = Mystery"], ["director = \"Jordan Peele\""]])
```

The bug comes on
Xcode 13.2
Using SPM 
Meilisearch Version 0.12.0

**Comment by curquiza** [comment]
Hello @ravisharmaa, thanks for the report!
I moved the issue to the meilisearch-swift repo so that the maintainer (@bidoubiwa) can help you with your problem!

**Comment by bidoubiwa** [comment]
Hey @ravisharmaa 
Thanks for raising this error :)  This will need to be fixed [here](https://github.com/meilisearch/meilisearch-swift/blob/f322911570ae4d7836fd6f1bce49d1dec6ba12b2/.code-samples.meilisearch.yaml#L912) asap 

Indeed you can also create [filters in a filter format](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#using-filters).

For example: 
```
(genres = horror OR genres = comedy) AND release_date > 795484800
```

**Comment by ravisharmaa** [comment]
@bidoubiwa Thank you for the prompt response.

**Comment by ravisharmaa** [comment]
> Hey @ravisharmaa Thanks for raising this error :) This will need to be fixed [here](https://github.com/meilisearch/meilisearch-swift/blob/f322911570ae4d7836fd6f1bce49d1dec6ba12b2/.code-samples.meilisearch.yaml#L912) asap
> 
> Indeed you can also create [filters in a string format](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#using-filters).
> 
> For example:
> 
> ```
> (genres = horror OR genres = comedy) AND release_date > 795484800
> ```

@bidoubiwa This means array support for filters is wip?

**Comment by ppamorim** [comment]
@ravisharmaa Array support is not required since you can translate your filter into a string that Meilisearch can understand. It's more simple. :)

**Comment by bidoubiwa** [comment]
> @bidoubiwa This means array support for filters is wip or a typo in the documentation?

It is a mistake in the documentation!

**Comment by ravisharmaa** [comment]
@bidoubiwa Thank you for clearing it out. You can resolve the issue at your ease or shall I close this issue?

**Comment by bidoubiwa** [comment]
We keep it open until we did not fix the issue. The sample is on this repo [here](https://github.com/meilisearch/meilisearch-swift/blob/f322911570ae4d7836fd6f1bce49d1dec6ba12b2/.code-samples.meilisearch.yaml#L912). 

Feel free to contribute to fix it! No problem if you don't have time :)

**Comment by brunoocasali** [comment]
I'm going to close this since, some of SDKs will not be able to support string filters or array filters (we can't ensure that)
