### ISSUE TITLE
Remove sys-info routes

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-swift#25]
As stated in https://github.com/meilisearch/MeiliSearch/pull/810 and https://github.com/meilisearch/integration-guides/issues/36 the sys-info routes will be considered as deprecated in MeiliSearch v0.13.0. These routes should be removed from this SDK accordingly.

**Comment by Ethenyl** [comment]
Hi @eskombro, @curquiza,

I'm available to work on the issue if it's good for you folks, is it still available?

Thanks.

**Comment by Ethenyl** [comment]
I've created the PR #50 to remove the sys-info routes.

**Comment by curquiza** [comment]
Hello @Ethenyl! Thanks for your PR! We are going to review :)
