### ISSUE TITLE
The Authorization header is missing. It must use the bearer authorization method.

### ISSUE THREAD

**Issue by mdotadil** [meilisearch/meilisearch-swift#251]
MeiliSearchApiError: The Authorization header is missing. It must use the bearer authorization method.
code: missing_authorization_header
type: auth
link: Optional("https://docs.meilisearch.com/errors#missing_authorization_header")
status: 401

- MeiliSearch (0.12.0)

**Comment by bidoubiwa** [comment]
Hey @mdotadil , this issue will be fixed once this PR has been merged #243 

Meanwhile the package is compatible with meilisearch v0.24.0
