### ISSUE TITLE
Changes dates represented as strings to dates represented as a Date type

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#254]
**Description**
In the task structure multiple fields represents dates but are typed as `strings`. It would be an improvement to change these dates to  a `Date` type object and not a string, 

Example can be found here: 

https://github.com/meilisearch/meilisearch-swift/blob/ae7ad35829ebaedebc0dd050c05703207d55c819/Sources/MeiliSearch/Model/Task.swift#L34

Currently the decoder is not able to transform the returned date format by Meilisearch into a `Date` object in swift. See error: 
```
▿ Swift.DecodingError.dataCorrupted
  ▿ dataCorrupted: Swift.DecodingError.Context
    ▿ codingPath: 1 element
      - CodingKeys(stringValue: "duration", intValue: nil)
    - debugDescription: "Date string does not match format expected by formatter."
    - underlyingError: nil

```

Meilisearch is returned date the following way:

```
   "enqueuedAt": "2021-08-10T14:29:17.000000Z",
```
Which [per the specs](https://github.com/meilisearch/specifications/blob/bf097e2495eb39f3702b69d804f7442d6a9cd53f/text/0060-tasks-api.md?plain=1#L67) is described like this (for example with enqueuedAt): 

```
| enqueuedAt | string | Represent the date and time as `ISO-8601` format when the task has been enqueued |
```

**Comment by brunoocasali** [comment]
I had a similar problem when upgrading the dart SDK: https://github.com/meilisearch/meilisearch-dart/blob/main/lib/src/client_impl.dart#L160 so I had to make a workaround in order to be able to serialize it. 
Not sure if helps 👯

**Comment by bidoubiwa** [comment]
For the moment there are two API in swift. One called Date that has a [`ISO8601Format(_:)`](
https://developer.apple.com/documentation/foundation/date/3766420-iso8601format) method but only compatible with MacOS 12+
The other is called [`DateFormatter`](https://developer.apple.com/documentation/foundation/dateformatter) and I believe with this API it is easy
