### ISSUE TITLE
Clean code duplication in HTTP request structure

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#255]
For the moment in the [Requests](https://github.com/meilisearch/meilisearch-swift/blob/main/Sources/MeiliSearch/Request.swift) structure there is a lot of code duplication. 

The better idea would be to have one function used by all the methods: `post`,`get`,`patch`,`put` that would set up the request object and make the request.

**Comment by brunoocasali** [comment]
I think this issue was closed by the efforts applied here https://github.com/meilisearch/meilisearch-swift/pull/283

If I'm mistaken, feel free to reopen this issue @bidoubiwa
