### ISSUE TITLE
Remove unit tests par as integration tests covers the same

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#258]
As of now we have two sections in our tests

- IntegrationsTests
- UnitTests

Unittests works by mocking the answer of the HTTP requests. While these might be very interesting, as of today they are not compatible with the ever changing API of Meilisearch. 

It will be interesting to mock meilisearch once it has an official release in v1 but until then it requires additional maintenance for not a lot of added value. 

What do you think?

**Comment by brunoocasali** [comment]
We are on the road to v1 soon, and it may be time to rethink the whole structure of tests in all of the SDKs we maintain. Given that we can keep these tests, they may be helpful for future implementations.
