### ISSUE TITLE
How to make integrations tests more readable?

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#262]
Integrations tests are made against a running Meilisearch instance. Thus they are asynchronous. Which means that if we need to test a function that requires a setup. A cascade hells starts. 

This solution is certainly not the best. How do you think we should go on with this?

Example in this function: 

https://github.com/meilisearch/meilisearch-swift/blob/9ed96cb0efb8bdc23e9d26d6ec3c77381ea18091/Tests/MeiliSearchIntegrationTests/DocumentsTests.swift#L62

**Comment by brunoocasali** [comment]
That's still an issue, but I don't think this is relevant anymore compared to other implementations that could be made here, so I'll close this.
