### ISSUE TITLE
Add "try" in the code samples

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-swift#322]
Add `try` mark to `.code-samples.meilisearch.yml` where it's needed:

example:

```swift
let client = MeiliSearch(host: "http://localhost:7700", apiKey: "apiKey")
```
new:
```swift
let client = try MeiliSearch(host: "http://localhost:7700", apiKey: "apiKey")
```

because the MeiliSearch constructor can throw an error if the host is invalid.

**Comment by mgregoire254** [comment]
Hi.  I would like to work on this.  If I'm understanding correctly, you would like try added wherever there is a connection attempt within the .yml file?

**Comment by brunoocasali** [comment]
Yes, @mgregoire254 

The `MeiliSearch()` constructor can throw errors if there is some error, and in the `.code-samples.meilisearch.yml`, we have multiple places where the `try` keyword is missing. The idea is really simple just the keyword should solve the issue :)
