### ISSUE TITLE
Primary key should be optionnal in documents addition routes

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#33]
## Problem

The `primaryKey` parameter is not optionnal and is misleading since giving it a value of `""` like the tests did makes MeiliSearch believe that the primaryKey's name is indeed `""`. 
Because of that, documents are not added in these cases:

```swift
self.client.addDocuments(
            UID: uid,
            documents: documents,
            primaryKey: ""
        )
```

MeiliSearch returns the following error: 
```
    "error": "document id is missing",
```

To let MeiliSearch infer the primary key one should give `nil` as a value to the primaryKey
```swift
self.client.addDocuments(
            UID: uid,
            documents: documents,
            primaryKey: nil
        )
```

Which is a lot to write and is not scalable with new parameters that could come in the next versions of MeiliSearch.

## Solutions

In order to not have to write `primaryKey` each time document are added the parameter should become optionnal.

### Implementation

This is done by adding a default value in the function parameters: 

```swift
func addOrReplace(
        _ UID: String,
        _ document: Data,
        _ primaryKey: String? = nil ,
        _ completion: @escaping (Result<Update, Swift.Error>) -> Void) {
```

```swift
func addOrUpdate(
        _ UID: String,
        _ document: Data,
        _ primaryKey: String? = nil,
        _ completion: @escaping (Result<Update, Swift.Error>) -> Void) {
```

```swift 
public func addDocuments(
        UID: String,
        documents: Data,
        primaryKey: String? = nil,
        _ completion: @escaping (Result<Update, Swift.Error>) -> Void) {
        self.documents.addOrReplace(
            UID,
            documents,
            primaryKey,
            completion)
    }
```

```swift
   public func updateDocuments(
        UID: String,
        documents: Data,
        primaryKey: String? = nil,
        _ completion: @escaping (Result<Update, Swift.Error>) -> Void) 
```

### tests

- [ ] Tests without Primary Key
- [ ] Tests with Primary Key

I would like your opinion on my suggestion @ppamorim

**Comment by ednofedulo** [comment]
can i work on this?

**Comment by curquiza** [comment]
Hello @ednofedulo! Yes! Go for it 🚀 thanks
