### ISSUE TITLE
No public initializers for `KeyParams` and `KeysQuery` structs.

### ISSUE THREAD

**Issue by mannuch** [meilisearch/meilisearch-swift#335]
Hello!

The `KeyParams` and `KeysQuery` structs do not have publicly accessible initializers. This implies that any code outside the `MeiliSearch` module cannot create new instances of these structs.

This works in direct contrast to examples laid out in the Meilisearch documentation such as when it displays constructing new `KeyParams` instances to pass to the `POST /keys` endpoint, which can be seen [here](https://docs.meilisearch.com/learn/security/master_api_keys.html#creating-an-api-key), if you select Swift as the client language.

Thanks!

`meilisearch-swift v0.14.1`

**Comment by curquiza** [comment]
Hello @mannuch thanks for having opened this issue! 😄 Reviewing your PR today!
