### ISSUE TITLE
v0.29: Add support to matchingPolicy search request parameter

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-swift#341]
This improvement motivation is about letting the user customize the behavior of Meilisearch when retrieving documents according to the query words.

- Add a `matchingStrategy` parameter to search requests via `SearchParameters`.
- The value last is the default strategy if the field is not specified.
- This field can receive only two valid options `last` or `all`.

Expected result:

```swift
let searchParameters = SearchParameters(
    query: "shifu",
    matchingStrategy: "last",
    attributesToCrop: ["overview"],
    cropMarker: "[…]"
)

client.index("movies").search(searchParameters) { (result) in ... }
```

Good to have: Make the `last` or `all` constants where we can quickly use them without mistakes.

**Comment by curquiza** [comment]
Closing this one, too old, so can collide with the current code samples. We will run our own tool to define the missing code sample
