### ISSUE TITLE
primary Key parameter missing on index creation

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-swift#35]
## Problem
The primary key should be an optionnal parameter given on index creation. 

See [create index reference documentation](https://docs.meilisearch.com/references/indexes.html#create-an-index)

```bash
$ curl \
  -X POST 'http://localhost:7700/indexes' \
  --data '{
    "uid": "movies",
    "primaryKey": "movie_id"
  }'
```

As per it works today, it does not have that parameter:

```swift
public func createIndex(
        UID: String,
        _ completion: @escaping (Result<Index, Swift.Error>) -> Void) {
        self.indexes.create(UID, completion)
    }

    public func getOrCreateIndex(
        UID: String,
        _ completion: @escaping (Result<Index, Swift.Error>) -> Void) {
        self.indexes.getOrCreate(UID, completion)
    }
```
## Solution

We should add `primaryKey` as an optionnal parameter with a default value of `nil` in the following routes: 
- createIndex
- getOrCreateIndex

**Comment by curquiza** [comment]
Closed with #32
