### ISSUE TITLE
Typo Fix in README.md

### ISSUE THREAD

**Issue by Dishant10** [meilisearch/meilisearch-swift#350]
There's a typo in the README.md, I would like to fix it. I'll also link a PR with this issue. 
The typo is with the Getting Started section in the README.md. 
MISTAKE :- 
To do a simply search using the client, you can create a Swift script like this:
FIX :- 
To do a simple search using the client, you can create a Swift script like this:

<img width="642" alt="Screenshot 2022-10-31 at 9 11 55 PM" src="https://user-images.githubusercontent.com/84343829/199048920-d26106b2-2772-4add-baff-a7e0132ee49c.png">

**Comment by Dishant10** [comment]
If this is a genuine fix. I would love to work on this and it would be great if you can assign this task to me.
I created this issue to make the maintainers aware of this typo.
Thank you!

**Comment by brunoocasali** [comment]
Yes @Dishant10 go ahead send the PR :)

**Comment by Dishant10** [comment]
Sure!
