### ISSUE TITLE
Make the type of a Task a enum of values

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-swift#363]
In `/Sources/MeiliSearch/Model/Task.swift`:

The attribute `public let type: String` should become an enum.
The possible values are: 
```
indexCreation, indexUpdate, indexDeletion, indexSwap, documentAdditionOrUpdate, documentDeletion, settingsUpdate, dumpCreation, taskCancelation, taskDeletion, and snapshotCreation
```

**Comment by Dishant10** [comment]
Hii,
I would like to fix this issue. Please assign this issue to me and if possible please mention any extra information that is required apart from the above statement.
Thank you!!

**Comment by brunoocasali** [comment]
Hi! @Dishant10. Good to see you again!

This issue is very straightforward! Something I could add to it is the value of the enum should be sent as camelCase eg. "indexUpdate", even if the enum key is `INDEX_UPDATE`.

You don't need to be assigned to the issue, we usually don't do it since people may not come back! And this could prevent other potential developers to contribute!

See you soon! Let me know if you have any doubts!

**Comment by Dishant10** [comment]
Got it! Let me try this one. I'll ask if I get stuck somewhere. 
Thank you!!!

**Comment by Dishant10** [comment]
I've raised a PR, please review it. I'll make any changes if needed.
Thank you!!
