### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by navanchauhan** [meilisearch/meilisearch-swift#377]
I was planning on integrating Meilisearch into an iOS/macOS app at some point, but it looks like this library is not on par with features released in meilisearch core. Do you need help maintaining this project?

**Comment by bidoubiwa** [comment]
Hey @navanchauhan 
Just to let you know @brunoocasali is on Holiday and will answer your question once he comes back.

Meanwhile, which feature are you referring to? Could you update your title with a bit more context? Like `missing features: x,y,z`.

**Comment by navanchauhan** [comment]
I haven’t started using it in my app yet, but it seems like meilisearch-swift is currently not on par with other clients. I don’t have any special requests right now, but I am happy to work on making this feature complete.

For example, all the currently open issues on this repository.

Best,

Navan

**Comment by bidoubiwa** [comment]
Hey @navanchauhan,

That would be awesome :) Indeed swift does not include all latest features introduces in the new releases of Meilisearch. If you have time to add some of them that would be of great help 🔥🙏

**Comment by brunoocasali** [comment]
Hi @navanchauhan! First, thanks for this introduction. I would appreciate any help!

I don't have much to add to @bidoubiwa's message, but in any case, to reiterate, **this SDK works** and **it is actively maintained** and **you can safely use it in production**.

The fact is that most of the new features are not implemented right away. Instead, we ask for help from the community like in other SDKs we maintain. If any critical bug is found we will fix it ;)

So, yeah, you can use it and also can contribute, I would be delighted to review your PRs :)
