### ISSUE TITLE
Impossible to release to cocoapod

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-swift#442]
Swift release failed: impossible to publish to Cocoapods: https://github.com/meilisearch/meilisearch-swift/actions/runs/8360859280/job/22887494524

Reason: authentication issue. 

<img width="1155" alt="Capture d’écran 2024-03-20 à 17 17 26" src="https://github.com/meilisearch/meilisearch-swift/assets/20380692/87b4b479-22e9-448b-8a2a-c4dd610602ba">

I don't know why our token suddenly does not work. We changed nothing our side, and the token is still accessible by the CI

@Sherlouk if you have any clue 🙏

**Comment by curquiza** [comment]
I even realize v0.15.0 of this library is not even on cocoapod despite the CI succeeded some months ago

<img width="1233" alt="Capture d’écran 2024-03-20 à 17 18 52" src="https://github.com/meilisearch/meilisearch-swift/assets/20380692/6da4f9f8-78cc-426e-b082-224324463af5">

<img width="1147" alt="Capture d’écran 2024-03-20 à 17 19 36" src="https://github.com/meilisearch/meilisearch-swift/assets/20380692/c447c2fc-e5ac-4fea-8a56-4fbd90446ff0">

Did I miss something related to cocoapod in the swift world?

**Comment by Sherlouk** [comment]
Likely just needs the token to be updated. Haven't touched CocoaPods in years (most users are transitioning over to SPM at this point) - but likely just need to run `pod trunk register <email>` and get yourself a freshly authenticated token. Seems to have just expired which can happen with time and little use.

**Comment by curquiza** [comment]
Thank you @Sherlouk 
the issue is, I don't know how to re-generate a new token!
No command to do it, and nothing in the guide to automate the process

<img width="649" alt="Capture d’écran 2024-03-20 à 17 57 05" src="https://github.com/meilisearch/meilisearch-swift/assets/20380692/a0073938-4149-4160-b5d5-a7d9f294d2a1">

https://guides.cocoapods.org/making/getting-setup-with-trunk.html


Sorry, feel like a noob here 😅

**Comment by Sherlouk** [comment]
This isn't a noob moment, this isn't your skill set and that's absolutely fine.

Following the guide you sent above, you're able to run `pod trunk register` with various parameters (namely your email address). This will send you an email to authenticate and ensure you're the owner of the package with the right permissions.

Once you're fully registered you can run `pod trunk me --verbose` which will dump out a request to trunk.cocoapods.org. In this you'll see a `Authorization: Token XXXXXXXXXXX`. The token being what needs uploading to GitHub secets!

**Comment by curquiza** [comment]
it worked 🎉 

thank you @Sherlouk ❤️
