### ISSUE TITLE
Remove acceptNewFields

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-swift#48]
According to this issue https://github.com/meilisearch/integration-guides/issues/39

**Comment by Ethenyl** [comment]
Hi @curquiza,

I would like to be assigned to this issue, is it still available?

Thanks.

**Comment by curquiza** [comment]
Hello @Ethenyl! yes it is! I assign you! 😁
Thanks for your involvement!

**Comment by Ethenyl** [comment]
I have created #51 to fix this issue.
