### ISSUE TITLE
facetsDistribution is missing in SearchResult model

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-swift#58]
`facetsDistribution` is missing in [this file](https://github.com/meilisearch/meilisearch-swift/blob/3f761795f4b1b3ef3d451dfd541bbab2622c636d/Sources/MeiliSearch/Model/SearchResult.swift).

- [ ] add in the code
- [ ] add search test

**Comment by ppamorim** [comment]
This is fixed in the PR #54.
