### ISSUE TITLE
waitForPendingUpdate method

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-swift#6]
Issue fully detailed [here](https://github.com/meilisearch/integration-guides/issues/1).

**Comment by ppamorim** [comment]
@curquiza Is this feature really needed? The Swift library is 100% async by design.

**Comment by bidoubiwa** [comment]
Hey @ppamorim ppamorim! 
I think there are two different "asynchronicity". 
1. The asynchronicity of the httprequest. Where you have to wait for MeiliSearch Server to respond
2. The asynchronicity of MeiliSearch processes. Where you have to wait for your actions to be `proccessed` by MeiliSearch. ([More info here](https://docs.meilisearch.com/guides/advanced_guides/asynchronous_updates.html))

This function aims to create a waiting function for the second case, not the first/

When I look into your tests I observe this 
```swift
   self.client.addOrReplaceDocument(
            UID: uid,
            document: document,
            primaryKey: primaryKey) { result in

            switch result {
            case .success(let update):
                XCTAssertEqual(stubUpdate, update)
                expectation.fulfill()
            case .failure:
                XCTFail("Failed to add or replace Movies document")
            }

        }

        self.wait(for: [expectation], timeout: 1.0)
```

If I read your code correctly. On the last line of this code block, you wait for `addOrReplaceDocument` to be `fulfilled` and you consider it to be fulfilled once MeiliSearch responded with the update information. This is the first case of asynchronicity discussed above.
But this does not mean that the addDocument has been processed by MeiliSearch. It is possibly still in the queue.

The idea with `waitForPendingUpdate` is that it waits for the second case of `asynchronicity` discussed above. I'm do not know any swift but let me make a pseudo code with it:

```swift
   self.client.addOrReplaceDocument(
            UID: uid,
            document: document,
            primaryKey: primaryKey) { result in

            switch result {
            case .success(let update):
               XCTAssertEqual(stubUpdate, update)
               self.client. waitForPendingUpdate(
                    UID: uid, 
                    updateId: update["updateId"]) { result in 
                    switch result {
                         case .success(let updateInfo):
                               XCTAssertEqual("processed", update.status)
                               expectation.fulfill()
                         case .failure:
                               XCTFail("Failed to add or replace Movies document")
                    }
            }

               }               
            case .failure:
                XCTFail("Failed to add or replace Movies document")
            }

        }

        self.wait(for: [expectation], timeout: 1.0)
```

This will ensur that the documents have been processed and thus added correctly to MeiliSearch. The user will be able to wait upon any asynchronous MeiliSearch process and not just the MeiliSearch server response. In this case, the user is now sure all of his documents have been added and he can use the search.

**Comment by ppamorim** [comment]
@bidoubiwa Oh nice I will implement this! Thank you for the complete explanation.
